const mongoose = require("mongoose");

const sceneSchema = new mongoose.Schema(
  {
    userId:      { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    characterId: { type: String, required: true },
    vibeId:      { type: String, required: true },
    videoUrl:    { type: String, required: true },
    cloudinaryPublicId: { type: String, required: true },
    duration:    { type: String, default: "0:05" },
    // Whether this scene was generated by extending a previous video
    isExtended:  { type: Boolean, default: false },
    sourceVideoUrl: { type: String, default: null },
  },
  { timestamps: true }
);

sceneSchema.index({ userId: 1, characterId: 1, createdAt: -1 });
sceneSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.models.Scene || mongoose.model("Scene", sceneSchema);
